export const SELECT_PRODUCT_GROUP = 'SELECT_PRODUCT_GROUP';
export const GET_PRODUCT_GROUPS = 'GET_PRODUCT_GROUPS';
export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET'
export const ADD_TO_BASKET_VIA_BARCODE = 'ADD_TO_BASKET_VIA_BARCODE'