export const SELECT_PRODUCT_GROUP = 'SELECT_PRODUCT_GROUP';
export const GET_PRODUCT_GROUPS = 'GET_PRODUCT_GROUPS';

export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET'
export const CLEAR_BASKET = 'CLEAR_BASKET'
export const ADD_TO_BASKET_VIA_BARCODE = 'ADD_TO_BASKET_VIA_BARCODE'
export const UPDATE_BASKET_ITEM_PRICE = 'UPDATE_BASKET_ITEM_PRICE'

export const CREATE_SALES_ORDER = 'CREATE_SALES_ORDER'

export const GET_CUSTOMER_ACCOUNTS = 'GET_CUSTOMER_ACCOUNTS'
export const CUSTOMER_SELECTED = 'CUSTOMER_SELECTED'
